# Generated by Django 2.1 on 2018-08-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180824_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
