# Generated by Django 2.1 on 2018-09-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
